name: vedika_healthcare
description: "Vedika - The health care app"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  carousel_slider: ^5.0.0
  dotted_border: ^2.1.0
  permission_handler: ^11.3.1
  geolocator: ^13.0.2
  url_launcher: ^6.3.1
  telephony: ^0.2.0
  mobile_number: ^3.0.0
  google_maps_flutter: ^2.10.0
  location: ^8.0.0
  google_api_headers: ^4.3.1
  flutter_google_places_hoc081098: ^2.0.0
  provider: ^6.1.2
  shared_preferences: ^2.5.2
  razorpay_flutter: ^1.3.7
  animated_notch_bottom_bar: ^1.0.3
  flutter_local_notifications: ^19.0.0
  intl: ^0.19.0
  file_picker: ^9.0.1
  lottie: ^3.3.1
  image_picker: ^1.1.2
  syncfusion_flutter_pdfviewer: ^28.2.9
  device_info_plus: ^11.3.0
  open_file: ^3.5.10
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5
  firebase_ui_auth: ^1.16.1
  dio: ^5.8.0+1
  connectivity_plus: ^6.1.3
  network_info_plus: ^6.1.3
  flutter_secure_storage: ^9.2.4
  firebase_storage: ^12.4.4
  jwt_decoder: ^2.0.1
  cached_network_image: ^3.3.1
  google_fonts: ^6.2.1
  fluttertoast: ^8.2.12
  timeline_tile: ^2.0.0
  web_socket_channel: ^3.0.2
  firebase_messaging: ^15.2.4
  logger: ^2.5.0
  get: ^4.7.2
  fl_chart: ^0.66.2
  awesome_snackbar_content: ^0.1.5
  awesome_dialog: ^3.2.1
  shimmer: ^3.0.0
  jitsi_meet_flutter_sdk: ^11.1.1
  clipboard: ^0.1.3
  percent_indicator: ^4.2.3
  socket_io_client: ^3.1.2
  phonepe_payment_sdk: ^3.0.0
  hive_flutter: ^1.1.0
  hive: ^2.2.3
  speech_to_text: ^7.0.0
  translator: ^1.0.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.8
  hive_generator: ^2.0.1

flutter:
  assets:
    - assets/health_concern/
    - assets/brands/
    - assets/offers/
    - assets/category/
    - assets/healthDays/
    - assets/animations/
    - assets/logo/



  uses-material-design: true

