name: vedika_healthcare
description: "Vedika - The health care app"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter



  # UI & widgets
  cupertino_icons: ^1.0.8
  carousel_slider: ^5.0.0
  dotted_border: ^3.1.0
  animated_notch_bottom_bar: ^1.0.3
  lottie: ^3.3.1
  google_fonts: ^6.2.1
  shimmer: ^3.0.0
  timeline_tile: ^2.0.0
  percent_indicator: ^4.2.3
  awesome_snackbar_content: ^0.1.5
  awesome_dialog: ^3.2.1
  photo_view: ^0.15.0
  scrollable_positioned_list: ^0.3.8
  device_preview: ^1.3.1

  # Permissions & device info
  permission_handler: ^12.0.1
  geolocator: ^14.0.2
  location: ^8.0.0
  device_info_plus: ^11.3.0
  sensors_plus: ^6.1.1
  connectivity_plus: ^6.1.3
  network_info_plus: ^6.1.3
  app_settings: ^6.1.1

  # Google & maps
  google_maps_flutter: ^2.10.0
  google_api_headers: ^4.3.1
  flutter_google_places_hoc081098: ^2.0.0
  flutter_polyline_points: ^3.0.1

  # Auth & Firebase
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.1
  firebase_storage: ^13.0.0
  cloud_firestore: ^6.0.0
  firebase_messaging: ^16.0.0
  firebase_ui_auth: ^3.0.0

  # Notifications
  flutter_local_notifications: ^17.2.3

  # Storage
  shared_preferences: ^2.5.2
  flutter_secure_storage: ^9.2.4
  hive_flutter: ^1.1.0
  hive: ^2.2.3

  # Network
  dio: ^5.8.0+1
  http: ^1.1.0
  socket_io_client: ^3.1.2
  web_socket_channel: ^3.0.2

  # Payments
  razorpay_flutter: ^1.3.7
  phonepe_payment_sdk: ^3.0.0

  # Multimedia
  file_picker: ^10.3.1
  image_picker: ^1.1.2
  camera: ^0.11.2
  cached_network_image: ^3.3.1
  record: ^6.0.0
  open_file: ^3.5.10
  jitsi_meet_flutter_sdk: ^11.1.1
  flutter_tts: ^4.2.3

  # PDF & Docs
  syncfusion_flutter_pdfviewer: ^30.2.5
  pdfx: ^2.9.1
  pdf: ^3.11.3
  printing: ^5.14.2
  flutter_html: ^3.0.0

  # AI / ML
  google_mlkit_text_recognition: ^0.15.0
  speech_to_text: ^7.3.0
  translator: ^1.0.3+1

  # Utils
  intl: ^0.20.2
  jwt_decoder: ^2.0.1
  logger: ^2.5.0
  get: ^4.7.2
  fluttertoast: ^8.2.12
  clipboard: ^2.0.2
  path_provider: ^2.1.2
  share_plus: ^11.0.0
  googleapis_auth: ^2.0.0
  googleapis: ^14.0.0

  # Charts
  fl_chart: ^1.0.0
  telephony: ^0.2.0
  mobile_number: ^3.0.0
  syncfusion_pdfviewer_linux: ^30.2.6
  syncfusion_pdfviewer_macos: ^30.2.6
  syncfusion_pdfviewer_windows: ^30.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  build_runner: ^2.4.8
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/health_concern/
    - assets/brands/
    - assets/offers/
    - assets/category/
    - assets/healthDays/
    - assets/animations/
    - assets/logo/
    - assets/ThirdPartyLogo/
    - assets/ai.png
    - assets/propane-analogy-453105-b8-dd3d3ffc61b0.json
    - assets/doctorsPic/
    - assets/Blogs/
    - assets/membership/
