// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4RBpkDfIFjPPoiQyP6LkHB_cILz-tekU',
    appId: '1:1021794706756:web:743a02ce8dda477751e311',
    messagingSenderId: '1021794706756',
    projectId: 'vedikahealthcare-59980',
    authDomain: 'vedikahealthcare-59980.firebaseapp.com',
    storageBucket: 'vedikahealthcare-59980.firebasestorage.app',
    measurementId: 'G-8KJ946S3EF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAaUxHDjaVykZnUOOgS1no2xTkUXbobAy0',
    appId: '1:1021794706756:android:f679ff4cd5128f3251e311',
    messagingSenderId: '1021794706756',
    projectId: 'vedikahealthcare-59980',
    storageBucket: 'vedikahealthcare-59980.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2_9-LYJ2FysinqaOUxZd8z-F_M19l26k',
    appId: '1:1021794706756:ios:e8d0f95edbb82c5b51e311',
    messagingSenderId: '1021794706756',
    projectId: 'vedikahealthcare-59980',
    storageBucket: 'vedikahealthcare-59980.firebasestorage.app',
    iosBundleId: 'com.vedika.heath.vedikaHealthcare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2_9-LYJ2FysinqaOUxZd8z-F_M19l26k',
    appId: '1:1021794706756:ios:e8d0f95edbb82c5b51e311',
    messagingSenderId: '1021794706756',
    projectId: 'vedikahealthcare-59980',
    storageBucket: 'vedikahealthcare-59980.firebasestorage.app',
    iosBundleId: 'com.vedika.heath.vedikaHealthcare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA4RBpkDfIFjPPoiQyP6LkHB_cILz-tekU',
    appId: '1:1021794706756:web:a1237e4d814cc74651e311',
    messagingSenderId: '1021794706756',
    projectId: 'vedikahealthcare-59980',
    authDomain: 'vedikahealthcare-59980.firebaseapp.com',
    storageBucket: 'vedikahealthcare-59980.firebasestorage.app',
    measurementId: 'G-JW86N45851',
  );
}
